services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  sortter:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - '8088:8088'